services:
  kaggle-identifying-age-related-conditions:
    build: ./Dockerfile
    container_name: kaggle-identifying-age-related-conditions
    hostname: kaggle-identifying-age-related-conditions
    shm_size: '28gb'
    deploy:
      resources:
        reservations:
          devices:
           - driver: nvidia
             capabilities: ["gpu"]
    volumes:
      - ${PWD}/:/workspace:cached
      - ${PWD}/kaggle:/kaggle:cached
      - ${PWD}/log/mlruns:/workspace/log/mlruns
    environment:
      TZ: Asia/Tokyo
      KAGGLE_USERNAME: ${KAGGLE_USERNAME}
      KAGGLE_KEY: ${KAGGLE_KEY}
      MLFLOW_TRACKING_URI: /workspace/log/mlruns
    tty: true
